### ISSUE TITLE
Where does zss dependencies work in the project?

### ISSUE THREAD

**Issue by wangshaonan** [mingdachen/disentangle-semantics-syntax#3]
Where does zss dependencies work in the project? I think may it is in eval_f1_acc.py, but I didn't find it.

**Comment by mingdachen** [comment]
It is used for computing tree edit distance, which hasn't been released yet. I will push the code soon. Sorry for the confusion.

**Comment by wangshaonan** [comment]
Thank you for your fast reply. Looking forward to it.
