### ISSUE TITLE
No such file or directory: '../syntactic evaluation//10_candidates.txt'

### ISSUE THREAD

**Issue by wangshaonan** [mingdachen/disentangle-semantics-syntax#4]
There are no 10_candidates.txt and 11_candidates.txt in syntactic evaluation file.

**Comment by mingdachen** [comment]
Hi, I just checked the google drive and there are the files you mentioned (see the following screenshot)

<img width="1042" alt="image" src="https://user-images.githubusercontent.com/18625540/59573208-a7ee7f80-9066-11e9-9778-0efab08e621f.png">

I guess there might be some download errors?

**Comment by wangshaonan** [comment]
Sorry for the easy question. It is download errors. I have tried to download the data several times and each time results in different files. Problem solved. Thank you.
